### ISSUE TITLE
It seems that the net structure is not yolov2,right?

### ISSUE THREAD

**Issue by kashiwachen** [shishichang/yolov2-tensorflow#6]
After reading your code, it seems that the net structure in yolo_net.py is the model of YOLOv1 instead of YOLOv2.
Is this my misunderstanding or what ?
Thx for your sharing

**Comment by violet17** [comment]
I think the net structure in yolo_net.py is the model of YOLOv1 instead of YOLOv2, too.

**Comment by Stinky-Tofu** [comment]
I think too

**Comment by ChenjingYu1993** [comment]
me too，it seems to be the structure of yolo1

**Comment by zhaoleizhang** [comment]
me too。

**Comment by zhouqiuqiu** [comment]
there is no anchors...

**Comment by WxlSky** [comment]
me too. It is YOLOv1
